# Generated by Django 5.0.7 on 2024-07-23 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'gif', 'png'])]),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='text_files/', validators=[django.core.validators.FileExtensionValidator(['txt'])]),
        ),
    ]
